export const DATA_FETCH_START = "DATA_FETCH_START";
export const DATA_FETCH_SUCCESS = "DATA_FETCH_SUCCESS";
export const DATA_FETCH_FAILURE = "DATA_FETCH_FAILURE";

export const USER_DATA_START = "USER_DATE_START";
export const USER_DATA_SUCCESS = "USER_DATA_SUCCESS";
export const USER_DATA_FAILURE = "USER_DATA_FAILURE";